nome_cliente = input('Digite o nome do cliente: ')
dia_venc = input('Digite o dia de vencimento: ')
mes_venc = input('Digite o mês de vencimento: ')
valor_fatura = input('Digite o valor da fatura: ')
print('Olá,',nome_cliente)
print('A sua fatura com vencimento em',dia_venc,'de',mes_venc,'no valor de R$',valor_fatura,'está fechada.')
